# .github/workflows/ip-info.yml
name: Run ngrok version

on:
  workflow_dispatch:  # lets you trigger it manually from GitHub UI

jobs:
  show-ip:
    runs-on: ubuntu-22.04

    steps:
      - name: Show IP address info
        run: ip a
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ngrok cache
        id: ngrok-cache
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/ngrok
          key: ngrok-bin-v3

      - name: Download ngrok if not cached
        if: steps.ngrok-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          cp $(which ngrok) ~/.local/bin/ngrok

      - name: Add ngrok to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run ngrok version
        run: ngrok version

      - name: Install SSH server
        run: |
          sudo apt-get install -y openssh-server
          sudo mkdir -p /var/run/sshd

      - name: Set runner password
        run: echo "runner:simple1pass" | sudo chpasswd

      - name: Allow root login with password
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
      
      #- name: Start SSH server
      # run: sudo /usr/sbin/sshd

      - name: Check sshd status
        run: ps aux | grep sshd

      - name: Check runner password hash
        run: sudo grep runner /etc/shadow

      - name: Cat if password was set
        run: cat /etc/ssh/sshd_config

      - name: Configure ngrok authtoken
        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start ngrok TCP tunnel for SSH in background
        run: |
          nohup ngrok tcp 22 --log=stdout > ngrok.log 2>&1 &
          sleep 5
          curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Show current user
        run: whoami
        
      - name: Verify root password login via ssh localhost
        run: |
          echo "simple1pass" | sshpass ssh -o StrictHostKeyChecking=no runner@localhost 'echo SSH login successful'

      - name: Wait 1 sec to keep tunnel open
        run: sleep 1

      - name: Show SSH auth logs (second to last)
        if: always()  # run even if previous steps fail
        run: sudo tail -n 20 /var/log/auth.log
        

